"""add_geo_estimation_to_detections

Revision ID: e38e744e4473
Revises: bdda0d792877
Create Date: 2026-03-24 17:02:15.821569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e38e744e4473'
down_revision = 'bdda0d792877'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detections', sa.Column('estimated_lat', sa.Float(), nullable=True))
    op.add_column('detections', sa.Column('estimated_lon', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detections', 'estimated_lon')
    op.drop_column('detections', 'estimated_lat')
    # ### end Alembic commands ###
